Repository wso2/carbon-kernel, pull requests merged in 2020-02, with the labels that each got.

#2577 Handle exceptions during scheduled cache cleanup
  core/javax.cache/src/main/java/org/wso2/carbon/caching/impl/CacheCleanupTask.java
Labels: Code-Quality-Review/Done, Functionality-Review/Done

#2580 Refactored group-id support feature interface methods.
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/UniqueIDUserStoreManager.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/Entity.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/Group.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/User.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2595 Fix NPE when redirectURI cookie contains tenant-dashboard
  core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/CarbonUILoginUtil.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2594 Improvement of SameSiteCookie
  core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/SameSiteCookie.java
  core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/ServletCookie.java
  core/org.wso2.carbon.tomcat.ext/src/main/java/org/wso2/carbon/tomcat/ext/transport/CarbonResponseWrapper.java
  core/org.wso2.carbon.tomcat.ext/src/main/java/org/wso2/carbon/tomcat/ext/transport/ResponseFacadeWrapper.java
Labels: Code-Quality-Review/Pending, Functionality-Review/Done

#2591 Implementation review : Improvements for group-id interface
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/UniqueIDUserStoreManager.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/Attribute.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/Claim.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/Entity.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/Group.java
  core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/User.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done, work-in-progress
